//screens.dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:provider/provider.dart';
import 'config.dart';
import 'models.dart';
import 'widgets.dart';
import 'qr_screens.dart';

// 1. SPLASH SCREEN
class SplashScreen extends StatefulWidget {
  const SplashScreen({Key? key}) : super(key: key);

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _scaleAnimation;
  late Animation<double> _fadeAnimation;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      duration: const Duration(milliseconds: 2000),
      vsync: this,
    );
    
    _scaleAnimation = Tween<double>(begin: 0.5, end: 1.0).animate(
      CurvedAnimation(parent: _controller, curve: Curves.elasticOut),
    );
    
    _fadeAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(parent: _controller, curve: Curves.easeIn),
    );
    
    _controller.forward();
    
    Timer(const Duration(seconds: 3), () {
      Navigator.pushReplacement(
        context,
        PageRouteBuilder(
          pageBuilder: (context, animation, secondaryAnimation) => const OnboardingScreen(),
          transitionsBuilder: (context, animation, secondaryAnimation, child) {
            return FadeTransition(opacity: animation, child: child);
          },
        ),
      );
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [AppColors.primary, AppColors.secondary],
          ),
        ),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ScaleTransition(
                scale: _scaleAnimation,
                child: Container(
                  width: 120,
                  height: 120,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(30),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.black.withOpacity(0.2),
                        blurRadius: 20,
                        offset: const Offset(0, 10),
                      ),
                    ],
                  ),
                  child: const Icon(
                    Icons.quiz,
                    size: 60,
                    color: AppColors.primary,
                  ),
                ),
              ),
              const SizedBox(height: 30),
              FadeTransition(
                opacity: _fadeAnimation,
                child: Column(
                  children: const [
                    Text(
                      'Smart Quiz',
                      style: TextStyle(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                    SizedBox(height: 10),
                    Text(
                      'Smart Quizzes. Smarter You.',
                      style: TextStyle(
                        fontSize: 16,
                        color: Colors.white70,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// 2. ONBOARDING SCREEN
class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({Key? key}) : super(key: key);

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen> {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  final List<OnboardingData> _pages = [
    OnboardingData(
      icon: Icons.psychology,
      title: 'AI-Generated Quizzes',
      description: 'Get personalized quizzes generated by AI based on your learning needs',
    ),
    OnboardingData(
      icon: Icons.timer,
      title: 'Timer & Scoring',
      description: 'Challenge yourself with timed quizzes and track your performance',
    ),
    OnboardingData(
      icon: Icons.trending_up,
      title: 'Adaptive Difficulty',
      description: 'Questions adapt to your skill level for optimal learning',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Align(
              alignment: Alignment.topRight,
              child: TextButton(
                onPressed: () => _goToLogin(),
                child: const Text('Skip'),
              ),
            ),
            Expanded(
              child: PageView.builder(
                controller: _pageController,
                onPageChanged: (index) {
                  setState(() {
                    _currentPage = index;
                  });
                },
                itemCount: _pages.length,
                itemBuilder: (context, index) {
                  return _buildPage(_pages[index]);
                },
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(20),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    children: List.generate(
                      _pages.length,
                      (index) => _buildDot(index == _currentPage),
                    ),
                  ),
                  CustomButton(
                    text: _currentPage == _pages.length - 1 ? 'Get Started' : 'Next',
                    onPressed: () {
                      if (_currentPage == _pages.length - 1) {
                        _goToLogin();
                      } else {
                        _pageController.nextPage(
                          duration: const Duration(milliseconds: 300),
                          curve: Curves.easeInOut,
                        );
                      }
                    },
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPage(OnboardingData data) {
    return Padding(
      padding: const EdgeInsets.all(40),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            width: 150,
            height: 150,
            decoration: BoxDecoration(
              color: AppColors.primary.withOpacity(0.1),
              shape: BoxShape.circle,
            ),
            child: Icon(
              data.icon,
              size: 80,
              color: AppColors.primary,
            ),
          ),
          const SizedBox(height: 40),
          Text(
            data.title,
            textAlign: TextAlign.center,
            style: const TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 20),
          Text(
            data.description,
            textAlign: TextAlign.center,
            style: TextStyle(
              fontSize: 16,
              color: Colors.grey[600],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDot(bool isActive) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      margin: const EdgeInsets.only(right: 8),
      width: isActive ? 24 : 8,
      height: 8,
      decoration: BoxDecoration(
        color: isActive ? AppColors.primary : Colors.grey[300],
        borderRadius: BorderRadius.circular(4),
      ),
    );
  }

  void _goToLogin() {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (context) => const LoginScreen()),
    );
  }
}

// 3. LOGIN/SIGNUP SCREEN
class LoginScreen extends StatefulWidget {
  const LoginScreen({Key? key}) : super(key: key);

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  bool _isLogin = true;
  bool _obscurePassword = true;

  @override
Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 40),
              Icon(
                Icons.quiz,
                size: 80,
                color: AppColors.primary,
              ),
              const SizedBox(height: 20),
              Text(
                _isLogin ? 'Welcome Back!' : 'Create Account',
                textAlign: TextAlign.center,
                style: const TextStyle(
                  fontSize: 28,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 40),
              CustomTextField(
                hint: 'Email',
                icon: Icons.email_outlined,
              ),
              const SizedBox(height: 16),
              CustomTextField(
                hint: 'Password',
                icon: Icons.lock_outline,
                obscureText: _obscurePassword,
                suffixIcon: IconButton(
                  icon: Icon(
                    _obscurePassword ? Icons.visibility_off : Icons.visibility,
                  ),
                  onPressed: () {
                    setState(() {
                      _obscurePassword = !_obscurePassword;
                    });
                  },
                ),
              ),
              if (_isLogin)
                Align(
                  alignment: Alignment.centerRight,
                  child: TextButton(
                    onPressed: () {},
                    child: const Text('Forgot Password?'),
                  ),
                ),
              const SizedBox(height: 24),
              CustomButton(
                text: _isLogin ? 'Login' : 'Sign Up',
                onPressed: () {
                  Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(builder: (context) => const MainScreen()),
                  );
                },
              ),
              const SizedBox(height: 20),
              Row(
                children: [
                  Expanded(child: Divider()),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16),
                    child: Text('OR'),
                  ),
                  Expanded(child: Divider()),
                ],
              ),
              const SizedBox(height: 20),
              OutlinedButton.icon(
                onPressed: () {},
                icon: Icon(Icons.g_mobiledata, size: 28),
                label: const Text('Continue with Google'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.all(16),
                ),
              ),
              const SizedBox(height: 16),
              OutlinedButton(
                onPressed: () {
                  Navigator.pushReplacement(
                    context,
                    MaterialPageRoute(builder: (context) => const MainScreen()),
                  );
                },
                child: const Text('Continue as Guest'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.all(16),
                ),
              ),
              const SizedBox(height: 20),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(_isLogin ? "Don't have an account? " : "Already have an account? "),
                  TextButton(
                    onPressed: () {
                      setState(() {
                        _isLogin = !_isLogin;
                      });
                    },
                    child: Text(_isLogin ? 'Sign Up' : 'Login'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

}
// 4. MAIN SCREEN WITH BOTTOM NAVIGATION
class MainScreen extends StatefulWidget {
const MainScreen({Key? key}) : super(key: key);
@override
State<MainScreen> createState() => _MainScreenState();
}
class _MainScreenState extends State<MainScreen> {
int _currentIndex = 0;
final List<Widget> _screens = [
const HomeScreen(),
const CategoriesScreen(),
const HistoryScreen(),
const ProfileScreen(),
];
@override
Widget build(BuildContext context) {
return Scaffold(
body: _screens[_currentIndex],
bottomNavigationBar: Container(
decoration: BoxDecoration(
boxShadow: [
BoxShadow(
color: Colors.black.withOpacity(0.1),
blurRadius: 10,
),
],
),
child: BottomNavigationBar(
currentIndex: _currentIndex,
onTap: (index) {
setState(() {
_currentIndex = index;
});
},
type: BottomNavigationBarType.fixed,
selectedItemColor: AppColors.primary,
unselectedItemColor: Colors.grey,
items: const [
BottomNavigationBarItem(
icon: Icon(Icons.home_outlined),
activeIcon: Icon(Icons.home),
label: 'Home',
),
BottomNavigationBarItem(
icon: Icon(Icons.category_outlined),
activeIcon: Icon(Icons.category),
label: 'Categories',
),
BottomNavigationBarItem(
icon: Icon(Icons.history),
activeIcon: Icon(Icons.history),
label: 'History',
),
BottomNavigationBarItem(
icon: Icon(Icons.person_outline),
activeIcon: Icon(Icons.person),
label: 'Profile',
),
],
),
),
);
}
}
// 5. HOME DASHBOARD - Enhanced
class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with SingleTickerProviderStateMixin {
  late AnimationController _animationController;
  late Animation<double> _fadeAnimation;

  @override
  void initState() {
    super.initState();
    _animationController = AnimationController(
      duration: const Duration(milliseconds: 800),
      vsync: this,
    );
    _fadeAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(parent: _animationController, curve: Curves.easeIn),
    );
    _animationController.forward();
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    
    return Scaffold(
      body: SafeArea(
        child: FadeTransition(
          opacity: _fadeAnimation,
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Hello, User!',
                          style: TextStyle(
                            fontSize: 28,
                            fontWeight: FontWeight.bold,
                            color: isDark ? AppColors.darkText : AppColors.lightText,
                          ),
                        ),
                        const SizedBox(height: 6),
                        Text(
                          'Ready for today\'s challenge?',
                          style: TextStyle(
                            color: isDark ? Colors.grey[400] : Colors.grey[600],
                            fontSize: 15,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ],
                    ),
                    Container(
                      decoration: BoxDecoration(
                        color: isDark ? AppColors.darkCard : AppColors.lightCard,
                        shape: BoxShape.circle,
                        border: Border.all(
                          color: isDark ? AppColors.darkCardBorder : AppColors.lightCardBorder,
                        ),
                      ),
                      child: IconButton(
                        onPressed: () {},
                        icon: Icon(
                          Icons.notifications_outlined,
                          color: isDark ? AppColors.darkText : AppColors.lightText,
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 30),
                Row(
                  children: const [
                    Expanded(
                      child: StatCard(
                        icon: Icons.quiz,
                        title: 'Quizzes',
                        value: '45',
                        color: AppColors.primary,
                      ),
                    ),
                    SizedBox(width: 12),
                    Expanded(
                      child: StatCard(
                        icon: Icons.star,
                        title: 'Avg Score',
                        value: '85%',
                        color: AppColors.accent,
                      ),
                    ),
                    SizedBox(width: 12),
                    Expanded(
                      child: StatCard(
                        icon: Icons.check_circle,
                        title: 'Accuracy',
                        value: '92%',
                        color: AppColors.secondary,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 30),
                Text(
                  'Quick Actions',
                  style: TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.bold,
                    color: isDark ? AppColors.darkText : AppColors.lightText,
                  ),
                ),
                const SizedBox(height: 16),
                ActionCard(
                  icon: Icons.play_circle_filled,
                  title: 'Start Quiz',
                  subtitle: 'Begin a new quiz challenge',
                  gradient: const LinearGradient(
                    colors: [AppColors.primary, AppColors.secondary],
                  ),
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => const QuizSetupScreen()),
                    );
                  },
                ),
                const SizedBox(height: 12),
                ActionCard(
                  icon: Icons.psychology,
                  title: 'AI Quiz',
                  subtitle: 'Generate quiz with AI',
                  gradient: const LinearGradient(
                    colors: [AppColors.secondary, Color(0xFFEC4899)],
                  ),
                  badge: 'AI',
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => const AIQuizScreen()),
                    );
                  },
                ),
                const SizedBox(height: 12),
                ActionCard(
                  icon: Icons.fitness_center,
                  title: 'Practice Mode',
                  subtitle: 'Practice without timer',
                  gradient: const LinearGradient(
                    colors: [AppColors.accent, Color(0xFF059669)],
                  ),
                  onTap: () {},
                ),
                const SizedBox(height: 12),
                ActionCard(
                  icon: Icons.create,
                  title: 'Create Quiz',
                  subtitle: 'Create and share your own quiz',
                  gradient: const LinearGradient(
                    colors: [Color(0xFF06B6D4), AppColors.primary],
                  ),
                  badge: 'NEW',
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => const CreateQuizScreen()),
                    );
                  },
                ),
                const SizedBox(height: 12),
                ActionCard(
                  icon: Icons.qr_code_scanner,
                  title: 'Scan QR',
                  subtitle: 'Join quiz by scanning QR code',
                  gradient: const LinearGradient(
                    colors: [AppColors.warning, Color(0xFFF97316)],
                  ),
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => const QRScannerScreen()),
                    );
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    ); 
  }
}

// 6. CATEGORIES SCREEN
class CategoriesScreen extends StatelessWidget {
const CategoriesScreen({Key? key}) : super(key: key);
@override
Widget build(BuildContext context) {
final categories = [
CategoryData('Science', Icons.science, Colors.blue, 45),
CategoryData('Math', Icons.calculate, Colors.orange, 38),
CategoryData('Programming', Icons.code, Colors.purple, 52),
CategoryData('Aptitude', Icons.psychology, Colors.green, 30),
CategoryData('History', Icons.history_edu, Colors.red, 25),
CategoryData('Geography', Icons.public, Colors.teal, 28),
];
return Scaffold(
  appBar: AppBar(
    title: const Text('Categories'),
    actions: [
      IconButton(
        onPressed: () {},
        icon: const Icon(Icons.search),
      ),
    ],
  ),
  body: Padding(
    padding: const EdgeInsets.all(20),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Choose a Category',
          style: TextStyle(
            fontSize: 24,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 20),
        Expanded(
          child: GridView.builder(
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              crossAxisSpacing: 16,
              mainAxisSpacing: 16,
              childAspectRatio: 1.1,
            ),
            itemCount: categories.length,
            itemBuilder: (context, index) {
              return CategoryCard(data: categories[index]);
            },
          ),
        ),
      ],
    ),
  ),
);
}
}
// 7. QUIZ SETUP SCREEN
class QuizSetupScreen extends StatefulWidget {
const QuizSetupScreen({Key? key}) : super(key: key);
@override
State<QuizSetupScreen> createState() => _QuizSetupScreenState();
}
class _QuizSetupScreenState extends State<QuizSetupScreen> {
int _questionCount = 10;
bool _timerEnabled = true;
String _difficulty = 'Medium';
@override
Widget build(BuildContext context) {
return Scaffold(
appBar: AppBar(
title: const Text('Quiz Setup'),
),
body: Padding(
padding: const EdgeInsets.all(20),
child: Column(
crossAxisAlignment: CrossAxisAlignment.stretch,
children: [
Container(
padding: const EdgeInsets.all(20),
decoration: BoxDecoration(
color: Theme.of(context).brightness == Brightness.dark
? AppColors.darkCard
: AppColors.lightCard,
borderRadius: BorderRadius.circular(16),
boxShadow: [
BoxShadow(
color: Colors.black.withOpacity(0.05),
blurRadius: 10,
offset: const Offset(0, 4),
),
],
),
child: Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: [
const Text(
'Number of Questions',
style: TextStyle(
fontSize: 16,
fontWeight: FontWeight.bold,
),
),
const SizedBox(height: 16),
Row(
mainAxisAlignment: MainAxisAlignment.spaceEvenly,
children: [5, 10, 15, 20].map((count) {
return ChoiceChip(
label: Text('$count'),
selected: _questionCount == count,
onSelected: (selected) {
setState(() {
_questionCount = count;
});
},
);
}).toList(),
),
],
),
),
const SizedBox(height: 20),
Container(
padding: const EdgeInsets.all(20),
decoration: BoxDecoration(
color: Theme.of(context).brightness == Brightness.dark
? AppColors.darkCard
: AppColors.lightCard,
borderRadius: BorderRadius.circular(16),
boxShadow: [
BoxShadow(
color: Colors.black.withOpacity(0.05),
blurRadius: 10,
offset: const Offset(0, 4),
),
],
),
child: Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: [
const Text(
'Difficulty Level',
style: TextStyle(
fontSize: 16,
fontWeight: FontWeight.bold,
),
),
const SizedBox(height: 16),
Row(
mainAxisAlignment: MainAxisAlignment.spaceEvenly,
children: ['Easy', 'Medium', 'Hard'].map((level) {
return DifficultyChip(
label: level,
selected: _difficulty == level,
onSelected: () {
setState(() {
_difficulty = level;
});
},
);
}).toList(),
),
],
),
),
const SizedBox(height: 20),
Container(
padding: const EdgeInsets.all(20),
decoration: BoxDecoration(
color: Theme.of(context).brightness == Brightness.dark
? AppColors.darkCard
: AppColors.lightCard,
borderRadius: BorderRadius.circular(16),
boxShadow: [
BoxShadow(
color: Colors.black.withOpacity(0.05),
blurRadius: 10,
offset: const Offset(0, 4),
),
],
),
child: Row(
mainAxisAlignment: MainAxisAlignment.spaceBetween,
children: [
Row(
children: const [
Icon(Icons.timer),
SizedBox(width: 12),
Text(
'Timer',
style: TextStyle(
fontSize: 16,
fontWeight: FontWeight.bold,
),
),
],
),
Switch(
value: _timerEnabled,
onChanged: (value) {
setState(() {
_timerEnabled = value;
});
},
),
],
),
),
const Spacer(),
CustomButton(
text: 'Start Quiz',
onPressed: () {
Navigator.push(
context,
MaterialPageRoute(
builder: (context) => QuizQuestionScreen(
questionCount: _questionCount,
timerEnabled: _timerEnabled,
),
),
);
},
),
],
),
),
);
}
}
// 8. QUIZ QUESTION SCREEN
class QuizQuestionScreen extends StatefulWidget {
final int questionCount;
final bool timerEnabled;
const QuizQuestionScreen({
Key? key,
required this.questionCount,
required this.timerEnabled,
}) : super(key: key);
@override
State<QuizQuestionScreen> createState() => _QuizQuestionScreenState();
}
class _QuizQuestionScreenState extends State<QuizQuestionScreen> with TickerProviderStateMixin {
int _currentQuestion = 0;
int? _selectedAnswer;
int _timeLeft = 30;
Timer? _timer;
late AnimationController _progressController;
final List<QuizQuestion> _questions = [
QuizQuestion(
question: 'What is the capital of France?',
options: ['London', 'Berlin', 'Paris', 'Madrid'],
correctAnswer: 2,
),
QuizQuestion(
question: 'Which planet is known as the Red Planet?',
options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
correctAnswer: 1,
),
];
@override
void initState() {
super.initState();
_progressController = AnimationController(
vsync: this,
duration: const Duration(seconds: 30),
);
if (widget.timerEnabled) {
  _startTimer();
}
}
void _startTimer() {
_progressController.forward();
_timer = Timer.periodic(const Duration(seconds: 1), (timer) {
if (_timeLeft > 0) {
setState(() {
_timeLeft--;
});
} else {
_nextQuestion();
}
});
}
void _nextQuestion() {
if (_currentQuestion < widget.questionCount - 1) {
setState(() {
_currentQuestion++;
_selectedAnswer = null;
_timeLeft = 30;
_progressController.reset();
});
if (widget.timerEnabled) {
_progressController.forward();
}
} else {
_finishQuiz();
}
}
void _finishQuiz() {
_timer?.cancel();
Navigator.pushReplacement(
context,
MaterialPageRoute(
builder: (context) => const ResultScreen(
score: 85,
totalQuestions: 10,
correctAnswers: 8,
),
),
);
}
@override
void dispose() {
_timer?.cancel();
_progressController.dispose();
super.dispose();
}
@override
Widget build(BuildContext context) {
final question = _questions[_currentQuestion % _questions.length];
return Scaffold(
  appBar: AppBar(
    title: Text('Question ${_currentQuestion + 1}/${widget.questionCount}'),
    actions: [
      if (widget.timerEnabled)
        Center(
          child: Padding(
            padding: const EdgeInsets.only(right: 16),
            child: Text(
              '$_timeLeft s',
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ),
    ],
  ),
  body: Column(
    children: [
      if (widget.timerEnabled)
        AnimatedBuilder(
          animation: _progressController,
          builder: (context, child) {
            return LinearProgressIndicator(
              value: 1 - _progressController.value,
              backgroundColor: Colors.grey[200],
              valueColor: AlwaysStoppedAnimation<Color>(
                _timeLeft <= 10 ? AppColors.error : AppColors.primary,
              ),
              minHeight: 6,
            );
          },
        ),
      Expanded(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Theme.of(context).brightness == Brightness.dark
                      ? AppColors.darkCard
                      : AppColors.lightCard,
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.05),
                      blurRadius: 10,
                    ),
                  ],
                ),
                child: Text(
                  question.question,
                  style: const TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              const SizedBox(height: 24),
              ...List.generate(question.options.length, (index) {
                return Padding(
                  padding: const EdgeInsets.only(bottom: 12),
                  child: QuizOptionTile(
                    option: question.options[index],
                    index: index,
                    selected: _selectedAnswer == index,
                    onTap: () {
                      setState(() {
                        _selectedAnswer = index;
                      });
                    },
                  ),
                );
              }),
            ],
          ),
        ),
      ),
      Padding(
        padding: const EdgeInsets.all(20),
        child: Row(
          children: [
            Expanded(
              child: OutlinedButton(
                onPressed: _nextQuestion,
                child: const Text('Skip'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.all(16),
                ),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              flex: 2,
              child: CustomButton(
                text: _currentQuestion == widget.questionCount - 1 ? 'Finish' : 'Next',
                onPressed: _selectedAnswer != null ? _nextQuestion : null,
              ),
            ),
          ],
        ),
      ),
    ],
  ),
);
}
}
// 9. RESULT SCREEN
class ResultScreen extends StatelessWidget {
final int score;
final int totalQuestions;
final int correctAnswers;
const ResultScreen({
Key? key,
required this.score,
required this.totalQuestions,
required this.correctAnswers,
}) : super(key: key);
@override
Widget build(BuildContext context) {
final accuracy = (correctAnswers / totalQuestions * 100).toInt();
return Scaffold(
  body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const SizedBox(height: 40),
              Container(
                width: 150,
                height: 150,
                decoration: BoxDecoration(
                  color: score >= 70 ? AppColors.accent : AppColors.warning,
                  shape: BoxShape.circle,
                  boxShadow: [
                    BoxShadow(
                      color: (score >= 70 ? AppColors.accent : AppColors.warning).withOpacity(0.4),
                      blurRadius: 30,
                      spreadRadius: 5,
                    ),
                  ],
                ),
                child: Center(
                  child: Icon(
                    score >= 70 ? Icons.emoji_events : Icons.sentiment_satisfied,
                    size: 80,
                    color: Colors.white,
                  ),
                ),
              ),
              const SizedBox(height: 30),
              Text(
                score >= 70 ? 'Excellent!' : 'Good Try!',
                style: const TextStyle(
                  fontSize: 32,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 10),
              Text(
                'You scored $score%',
                style: TextStyle(
                  fontSize: 24,
                  color: Colors.grey[600],
                ),
              ),
              const SizedBox(height: 40),
              Row(
                children: [
                  Expanded(
                    child: ResultStatCard(
                      icon: Icons.check_circle,
                      label: 'Correct',
                      value: '$correctAnswers',
                      color: AppColors.accent,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ResultStatCard(
                      icon: Icons.cancel,
                      label: 'Wrong',
                      value: '${totalQuestions - correctAnswers}',
                      color: AppColors.error,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ResultStatCard(
                      icon: Icons.percent,
                      label: 'Accuracy',
                      value: '$accuracy%',
                      color: AppColors.primary,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 40),
              CustomButton(
                text: 'View Details',
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => const DetailedAnalysisScreen(),
                    ),
                  );
                },
              ),
              const SizedBox(height: 12),
              OutlinedButton(
                onPressed: () {
                  Navigator.pushAndRemoveUntil(
                    context,
                    MaterialPageRoute(builder: (context) => const MainScreen()),
                    (route) => false,
                  );
                },
                child: const Text('Back to Home'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.all(16),
                  minimumSize: const Size(double.infinity, 50),
                ),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
);
}
}
// 10. DETAILED ANALYSIS SCREEN
class DetailedAnalysisScreen extends StatelessWidget {
const DetailedAnalysisScreen({Key? key}) : super(key: key);
@override
Widget build(BuildContext context) {
return Scaffold(
appBar: AppBar(
title: const Text('Detailed Analysis'),
),
body: ListView(
padding: const EdgeInsets.all(20),
children: [
const Text(
'Question Review',
style: TextStyle(
fontSize: 24,
fontWeight: FontWeight.bold,
),
),
const SizedBox(height: 20),
...List.generate(5, (index) {
return QuestionReviewCard(
questionNumber: index + 1,
question: 'What is the capital of France?',
userAnswer: 'Paris',
correctAnswer: 'Paris',
isCorrect: index % 2 == 0,
);
}),
],
),
);
}
}
// 11. HISTORY SCREEN
class HistoryScreen extends StatelessWidget {
const HistoryScreen({Key? key}) : super(key: key);
@override
Widget build(BuildContext context) {
return Scaffold(
appBar: AppBar(
title: const Text('Quiz History'),
actions: [
IconButton(
onPressed: () {},
icon: const Icon(Icons.filter_list),
),
],
),
body: ListView.builder(
padding: const EdgeInsets.all(20),
itemCount: 10,
itemBuilder: (context, index) {
return HistoryCard(
category: 'Science',
date: 'Dec ${28 - index}, 2025',
score: 85 - (index * 3),
questions: 10,
);
},
),
);
}
}
// 12. AI QUIZ SCREEN
class AIQuizScreen extends StatefulWidget {
const AIQuizScreen({Key? key}) : super(key: key);
@override
State<AIQuizScreen> createState() => _AIQuizScreenState();
}
class _AIQuizScreenState extends State<AIQuizScreen> {
final TextEditingController _promptController = TextEditingController();
String _difficulty = 'Medium';
@override
Widget build(BuildContext context) {
return Scaffold(
appBar: AppBar(
title: const Text('AI Quiz Generator'),
),
body: SingleChildScrollView(
padding: const EdgeInsets.all(20),
child: Column(
crossAxisAlignment: CrossAxisAlignment.stretch,
children: [
Container(
padding: const EdgeInsets.all(16),
decoration: BoxDecoration(
color: AppColors.primary.withOpacity(0.1),
borderRadius: BorderRadius.circular(12),
),
child: Row(
children: [
Container(
padding: const EdgeInsets.all(8),
decoration: BoxDecoration(
color: AppColors.primary,
borderRadius: BorderRadius.circular(8),
),
child: const Icon(
Icons.psychology,
color: Colors.white,
),
),
const SizedBox(width: 12),
Expanded(
child: Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: const [
Text(
'AI-Powered Quiz',
style: TextStyle(
fontWeight: FontWeight.bold,
fontSize: 16,
),
),
Text(
'Generate custom quizzes on any topic',
style: TextStyle(
fontSize: 12,
color: Colors.grey,
),
),
],
),
),
],
),
),
const SizedBox(height: 24),
const Text(
'Enter your topic',
style: TextStyle(
fontSize: 16,
fontWeight: FontWeight.bold,
),
),
const SizedBox(height: 12),
TextField(
controller: _promptController,
maxLines: 4,
decoration: InputDecoration(
hintText: 'e.g., "Generate Python programming MCQs about lists and dictionaries"',
border: OutlineInputBorder(
borderRadius: BorderRadius.circular(12),
),
filled: true,
),
),
const SizedBox(height: 24),
const Text(
'Select Difficulty',
style: TextStyle(
fontSize: 16,
fontWeight: FontWeight.bold,
),
),
const SizedBox(height: 12),
Row(
children: ['Easy', 'Medium', 'Hard'].map((level) {
return Expanded(
child: Padding(
padding: const EdgeInsets.only(right: 8),
child: DifficultyChip(
label: level,
selected: _difficulty == level,
onSelected: () {
setState(() {
_difficulty = level;
});
},
),
),
);
}).toList(),
),
const SizedBox(height: 40),
CustomButton(
text: 'Generate Quiz',
icon: Icons.auto_awesome,
onPressed: () {
showDialog(
context: context,
barrierDismissible: false,
builder: (context) => const Center(
child: Card(
child: Padding(
padding: EdgeInsets.all(24),
child: Column(
mainAxisSize: MainAxisSize.min,
children: [
CircularProgressIndicator(),
SizedBox(height: 16),
Text('Generating your quiz...'),
],
),
),
),
),
);
            Future.delayed(const Duration(seconds: 2), () {
              Navigator.pop(context);
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => const QuizQuestionScreen(
                    questionCount: 10,
                    timerEnabled: true,
                  ),
                ),
              );
            });
          },
        ),
      ],
    ),
  ),
);
}
}
// 13. PROFILE SCREEN
// 13. PROFILE SCREEN - Enhanced with Theme Toggle
class ProfileScreen extends StatefulWidget {
  const ProfileScreen({Key? key}) : super(key: key);

  @override
  State<ProfileScreen> createState() => _ProfileScreenState();
}

class _ProfileScreenState extends State<ProfileScreen> {
  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);
    final isDark = Theme.of(context).brightness == Brightness.dark;
    
    return Scaffold(
      appBar: AppBar(
        title: const Text('Profile'),
        actions: [
          IconButton(
            onPressed: () {},
            icon: const Icon(Icons.edit_outlined),
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(30),
              decoration: BoxDecoration(
                gradient: const LinearGradient(
                  colors: [AppColors.primary, AppColors.secondary],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
              ),
              child: Column(
                children: [
                  Container(
                    padding: const EdgeInsets.all(4),
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      border: Border.all(color: Colors.white, width: 3),
                    ),
                    child: const CircleAvatar(
                      radius: 50,
                      backgroundColor: Colors.white,
                      child: Icon(
                        Icons.person,
                        size: 50,
                        color: AppColors.primary,
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),
                  const Text(
                    'Aditya Suresh',
                    style: TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 16,
                      vertical: 8,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.white.withOpacity(0.25),
                      borderRadius: BorderRadius.circular(24),
                    ),
                    child: const Text(
                      'Level 5 - Intermediate',
                      style: TextStyle(
                        color: Colors.white,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Statistics',
                    style: TextStyle(
                      fontSize: 22,
                      fontWeight: FontWeight.bold,
                      color: isDark ? AppColors.darkText : AppColors.lightText,
                    ),
                  ),
                  const SizedBox(height: 16),
Row(
children: const [
Expanded(
child: StatCard(
icon: Icons.quiz,
title: 'Total Quiz',
value: '156',
color: AppColors.primary,
),
),
SizedBox(width: 12),
Expanded(
child: StatCard(
icon: Icons.emoji_events,
title: 'Badges',
value: '12',
color: AppColors.warning,
),
),
],
),
const SizedBox(height: 30),
Text(
'Settings',
style: TextStyle(
fontSize: 22,
fontWeight: FontWeight.bold,
color: isDark ? AppColors.darkText : AppColors.lightText,
),
),
const SizedBox(height: 16),
SettingsTile(
icon: Icons.dark_mode_outlined,
title: 'Dark Mode',
trailing: Switch(
value: themeProvider.isDark,
onChanged: (value) {
themeProvider.toggleTheme();
},
activeColor: AppColors.primary,
),
),
SettingsTile(
icon: Icons.language,
title: 'Language',
trailing: const Text(
'English',
style: TextStyle(
fontWeight: FontWeight.w500,
color: Colors.grey,
),
),
onTap: () {},
),
SettingsTile(
icon: Icons.notifications_outlined,
title: 'Notifications',
trailing: const Icon(Icons.chevron_right, color: Colors.grey),
onTap: () {},
),
SettingsTile(
icon: Icons.cloud_upload_outlined,
title: 'Cloud Backup',
trailing: const Icon(Icons.chevron_right, color: Colors.grey),
onTap: () {},
),
SettingsTile(
icon: Icons.wifi_off_outlined,
title: 'Offline Mode',
trailing: const Icon(Icons.chevron_right, color: Colors.grey),
onTap: () {},
),
SettingsTile(
icon: Icons.help_outline,
title: 'Help & Support',
trailing: const Icon(Icons.chevron_right, color: Colors.grey),
onTap: () {},
),
const SizedBox(height: 10),
SettingsTile(
icon: Icons.logout,
title: 'Logout',
titleColor: AppColors.error,
onTap: () {
Navigator.pushAndRemoveUntil(
context,
MaterialPageRoute(builder: (context) => const LoginScreen()),
(route) => false,
);
},
),
],
),
),
],
),
),
);
}
}

